/**
 * Universal Guardrails + Mandatory End-of-Session Reporting — appended, verbatim, to EVERY generated
 * agent file regardless of stack, target, or generation mode (single-stack, modular multi-stack, or
 * combined). These are intentionally stack-agnostic: they hold for a Python script exactly as much as a
 * React component, so they're written once here instead of being repeated (and risking drift) inside
 * every stack's entry in `stacks.ts`.
 *
 * In combined mode this text is included exactly ONCE at the end of the merged document — never once per
 * stack — which is what keeps a multi-stack `.agent.md` from ballooning with duplicated boilerplate.
 */

export const UNIVERSAL_GUARDRAILS_MD = `## Universal Guardrails
These four apply on top of the stack-specific directives above, to every language and framework this
agent touches, with no exceptions.

### 1. Code Optimization & Quality
- Write clean, production-ready code — not a proof of concept dressed up as a finished change.
- Remove unused imports, dead branches, and leftover debug statements before calling a change done.
- Avoid redundant computation (re-deriving a value already in scope, re-fetching data already available)
  and avoid patterns that leak memory or resources (unclosed handles, growing caches with no eviction,
  listeners never removed).

### 2. Error Handling & Validation
- Rigorous error checking and defensive programming at every boundary — a function should not trust the
  shape or presence of its inputs just because the type system says it should be there at compile time.
- Handle edge cases explicitly: empty collections, null/undefined/None, zero, negative numbers, boundary
  values, and malformed input.
- Handle network and I/O failures explicitly — timeouts, connection drops, non-2xx responses, partial
  writes — rather than assuming the happy path is the only path.

### 3. Token Efficiency
- Keep responses concise, structured, and direct — say what changed and why, not a running narration of
  every step taken to get there.
- Minimize filler commentary ("Great question!", restating the request back, apologizing preemptively) —
  every sentence should carry information the reader needs.
- Reference existing code by name/location instead of reprinting unchanged blocks "for context."

### 4. Security & Safety
- Prevent injection in every form relevant to this stack: SQL, NoSQL, command, template, and
  cross-site scripting (XSS) on anything rendered from user-controlled data.
- Never expose a secret, API key, credential or token — not in code, not in a commit, not in a log line,
  not in an error message returned to a client.
- Configure CORS and authentication/authorization deliberately and narrowly — no wildcard origins, no
  routes left unauthenticated by omission, no permissive default that "we'll tighten later."
- Validate input at every boundary that accepts it — both server-side API routes/handlers and client-side
  forms — client-side validation is a UX nicety, never the actual security control.`;

export const OPERATIONAL_GUARDRAILS_MD = `## Operational Guardrails & Safety Boundaries
A fixed permission tier for every action this agent might take in this repository — stack-agnostic,
applies whether the change is a one-line fix or a new module.

### 🟢 Always allowed, no need to ask
- Creating or extending unit and integration tests for existing or new logic.
- Refactoring an internal implementation without changing its public contract (function signature, API
  response shape, exported type).
- Updating local documentation, docstrings, inline comments, and \`README.md\` (see the mandatory sync rule
  below).
- Running linting, formatting, type-checking, and any other non-destructive, read-only verification command.

### 🟡 Ask first
- Adding or upgrading a top-level third-party dependency (\`package.json\`, \`requirements.txt\`,
  \`pyproject.toml\`, \`go.mod\`, \`Cargo.toml\`, or equivalent).
- Modifying a shared database schema or creating a new migration.
- Altering a core architectural abstraction, shared middleware, or any configuration that other modules
  depend on.
- Anything the person hasn't asked for and that isn't required to complete the stated task.

### 🔴 Never allowed
- Reading, modifying, or printing the contents of \`.env\`, \`.env.local\`, credentials, certificates, API
  keys, or any other secret value — even to "confirm" or "debug" them.
- Force-pushing or rewriting shared git history (\`git push --force\`, \`git reset --hard\` on a shared
  branch, deleting branches other than one just created for this change).
- Committing a lockfile edited by hand instead of regenerated by its package manager, or committing a large
  binary asset without being explicitly asked to.
- Disabling a lint, type, or security rule (\`eslint-disable\`, \`# type: ignore\`, \`# noqa\`, \`@ts-ignore\`,
  \`#[allow(...)]\`) to make a warning disappear instead of fixing the underlying issue, without saying so
  and getting confirmation first.`;

/** The fixed intro text for the per-stack "Verification Workflow" section built in masterAgent.ts — kept
 * here, next to the other one-time-per-document text, and combined at render time with the stack-specific
 * lint/type-check/test command table so the loop's wording never has to be duplicated per stack. */
export const SELF_VERIFICATION_LOOP_MD = `Follow this loop for every change, without waiting to be asked:
1. Make the targeted file change.
2. Run this stack's lint/format and type-check commands (see the table below).
3. Run the tests affected by the change.
4. If anything fails, read the actual output, fix the real cause, and re-run — don't hand a lint, type, or
   syntax error back to the person to debug when it's something this agent can fix directly.
5. Only report the task done once lint, type-check, and the affected tests all pass — or state explicitly,
   in the response, which check couldn't be run and why (e.g. no test runner configured yet).`;

export const GIT_WORKFLOW_MD = `## Git & Pull Request Conventions
- **Branch naming**: \`feat/<short-description>\` for a new capability, \`fix/<short-description>\` for a bug
  fix, \`refactor/<target-module>\` for a behavior-preserving restructure — match whatever convention this
  repo's existing branches already use if it differs.
- **Commit messages**: follow [Conventional Commits](https://www.conventionalcommits.org/) —
  \`feat(scope): add X\`, \`fix(scope): correct Y\`, \`test(scope): cover Z\` — unless the repo's git log shows
  it uses a different convention, in which case match that instead.
- **Pull request descriptions** should cover: (1) a short summary of what changed and why, (2) the
  verification steps actually run (lint/type-check/tests — see the Verification Workflow section), and (3)
  a screenshot or example payload when the change is user- or API-facing.`;

export const END_OF_SESSION_REPORTING_MD = `## Mandatory End-of-Session Reporting
At the conclusion of any code edits or task response, always provide a Markdown table outlining: (1) the
files/components modified, (2) the nature of the change, and (3) how the change impacts the application's
logic and business functionality. This is not optional and is not skipped for a small or single-file
change — a one-row table still applies.

Use this exact shape:

\`\`\`markdown
### 📊 Task Summary & Application Impact
| File / Component Changed | Type of Modification | Business & Functional Impact |
| :--- | :--- | :--- |
| \`src/components/Form.tsx\` | Added validation & state update | Prevents invalid payloads from hitting backend |
| \`app/api/endpoints.py\` | Added FastAPI response schema | Enforces strict type contracts & fixes CORS issue |
\`\`\`

The two rows above are an example of the *shape*, not literal content — populate it with whatever files
this task actually touched.`;
