import type { GeneratedFile } from "./types";
import type { Stack } from "./stacks";

/**
 * Optional add-on: a GitHub Actions workflow + a small, dependency-free shell script that actually
 * ENFORCES a handful of the guardrails from `templates/universalGuardrails.ts` in CI, instead of leaving
 * them as a markdown file an agent can silently ignore. This is the difference between "a rules file
 * that's a suggestion" and "a rules file with teeth": a PR that reintroduces a hard-coded secret, force
 * disables a lint rule, or commits a `.env` file fails CI on this check specifically, with a message that
 * points back at the guardrail it violated — the same one every agent working in this repo was told to
 * follow. It's intentionally grep-based and has zero dependencies (no Node/Python install step required)
 * so it runs in under a second on every PR, on every stack, with nothing else to configure.
 */

const CHECK_SCRIPT_PATH = "scripts/check-agent-guardrails.sh";
const WORKFLOW_PATH = ".github/workflows/agent-guardrails.yml";

function checkScript(stacks: Stack[]): string {
  const extraGlobs = [...new Set(stacks.flatMap((s) => s.fileGlobs))];
  return `#!/usr/bin/env bash
# Generated by Agent Hub — enforces a subset of the Operational Guardrails & Universal Guardrails that
# every generated agent file in this repo was told to follow (see .agent.md / CLAUDE.md / AGENTS.md).
# Zero dependencies on purpose: this must run in CI without an install step, on every stack.
set -euo pipefail

FAIL=0
say_fail() { echo "::error::$1"; FAIL=1; }

echo "Agent Hub guardrail check — scanning changed and tracked files..."

# Only check files git actually tracks, so build output / node_modules / vendored code never trips this.
FILES=\$(git ls-files | grep -Ev '(^|/)(node_modules|dist|build|\\.next|vendor|\\.venv|target)/' || true)

# --- Never Allowed: committed .env files (Operational Guardrails, "Never allowed") ---
ENV_FILES=\$(echo "\$FILES" | grep -E '(^|/)\\.env(\\..+)?\$' | grep -v '\\.env\\.example\$' || true)
if [ -n "\$ENV_FILES" ]; then
  say_fail "A .env file is tracked by git — secrets belong in environment/secret storage, never a committed file: \$ENV_FILES"
fi

# --- Never Allowed: an obvious hard-coded secret pattern (Universal Guardrails, Security & Safety) ---
if echo "\$FILES" | xargs -r grep -InE '(api[_-]?key|secret[_-]?key|access[_-]?token)\\s*[:=]\\s*["\\047][A-Za-z0-9_\\-]{16,}["\\047]' 2>/dev/null | grep -v -E '(\\.example|\\.sample|\\.md:)' ; then
  say_fail "A likely hard-coded secret/API key literal was found — read it from environment/secret storage instead."
fi

# --- Never Allowed: a lint/type rule silenced without explanation (Operational Guardrails, "Never allowed") ---
SUPPRESSIONS=\$(echo "\$FILES" | xargs -r grep -InE '(eslint-disable|# noqa|# type: ignore|@ts-ignore|#\\[allow\\()' 2>/dev/null || true)
if [ -n "\$SUPPRESSIONS" ]; then
  echo "::warning::Lint/type suppression(s) found — confirm each was discussed, not used to bypass a real issue:"
  echo "\$SUPPRESSIONS"
fi

# --- Never Allowed: a force-push marker left in a script, or a destructive git alias committed ---
if echo "\$FILES" | xargs -r grep -InE 'git (push --force|reset --hard)\\b' 2>/dev/null | grep -v -E '\\.md:' ; then
  say_fail "A destructive git command (--force / reset --hard) is committed in a script — this repo's guardrails forbid rewriting shared history."
fi

if [ "\$FAIL" -eq 1 ]; then
  echo ""
  echo "One or more Agent Hub guardrails were violated — see the errors above. These map directly to the"
  echo "Operational Guardrails / Universal Guardrails sections in this repo's agent instruction file(s)."
  exit 1
fi

echo "No guardrail violations found."
${extraGlobs.length > 0 ? `# Primary surface this check pays closest attention to (informational only): ${extraGlobs.join(", ")}` : ""}
`;
}

function workflowYaml(): string {
  return `# Generated by Agent Hub — runs the guardrail check on every push and pull request.
name: Agent Guardrails

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  guardrail-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Agent Hub guardrail check
        run: |
          chmod +x ${CHECK_SCRIPT_PATH}
          ./${CHECK_SCRIPT_PATH}
`;
}

/** Returns the two-file CI add-on (workflow + checker script) for the given stack selection, or `[]` when
 * the person hasn't opted in — this is additive and off by default so a first-time visitor gets the same
 * bundle as before; enabling it is a deliberate choice to put teeth behind the generated instructions. */
export function buildComplianceFiles(stacks: Stack[], enabled: boolean): GeneratedFile[] {
  if (!enabled) return [];
  return [
    { path: WORKFLOW_PATH, content: workflowYaml() },
    { path: CHECK_SCRIPT_PATH, content: checkScript(stacks) },
  ];
}
