import { JsonLd } from "@/components/JsonLd";
import { AgentHub } from "@/components/AgentHub";
import { faqLd, pageMetadata, softwareAppLd } from "@/lib/seo";

export const metadata = pageMetadata({
  title: "Agent Hub — Free Multi-Stack AI Coding Agent Generator",
  description:
    "Combine multiple technologies — e.g. Python + FastAPI + React + MongoDB — into one cross-stack-aware AI coding agent, or generate separate files per stack. Built-in Universal Guardrails (code quality, error handling, token efficiency, security) and a mandatory end-of-session impact chart, packaged for GitHub Copilot, Claude Code, Cursor, Windsurf, Cline, Continue.dev, Aider and AGENTS.md. Free, no sign-up, download as a zip.",
  path: "/",
  keywords: ["ai coding agent generator", "multi-stack ai agent", "github copilot instructions generator", "claude code CLAUDE.md generator", "cursor rules generator", "AGENTS.md generator"],
});

const FAQS = [
  {
    q: "What does Agent Hub generate?",
    a: "A ready-to-use bundle of files — the exact set depends on your stack(s), your generation mode, and which AI coding tool(s) you pick. Every file is built from the same consolidated Master Agent content: your stack's 10 Core Operating Directives, real best practices and anti-patterns, the Universal Guardrails (code quality, error handling, token efficiency, security), and a mandatory end-of-session Task Summary & Impact chart — all enforced together instead of scattered across separate instructions/agents/rules files.",
  },
  {
    q: "What's the difference between Combined and Modular mode?",
    a: "Combined (the default, recommended for multi-stack picks) merges every selected technology into one cross-stack-aware agent — plus a universal .agent.md at your repo root — so it understands how a frontend change reaches a backend endpoint or a database schema. Modular gives each stack its own independent file per tool instead, useful when different files should stay ownable by different people or teams. Tools with only one fixed root file (Windsurf, Aider, AGENTS.md) always get the merged content, since their format has no per-stack convention to split into.",
  },
  {
    q: "What are the Universal Guardrails?",
    a: "Four rules embedded in every generated file, combined or modular, regardless of stack: (1) Code Optimization & Quality — clean, production-ready code with no dead imports or leaked resources; (2) Error Handling & Validation — defensive programming and explicit edge cases at every boundary; (3) Token Efficiency — concise, structured responses with no filler; (4) Security & Safety — injection prevention, no exposed secrets, deliberate CORS/auth, and input validation on every API route and form. A fifth standing rule, Mandatory End-of-Session Reporting, requires a markdown Task Summary & Application Impact table at the end of every response.",
  },
  {
    q: "What are the 10 Core Operating Directives?",
    a: "Zero hallucination & codebase verification, strict type safety, bug prevention, token efficiency, comprehensive unit testing, OWASP & security standards, performance & resource management, architectural consistency, structured error handling, and — mandatory on every task — automatically syncing README.md with whatever changed.",
  },
  { q: "Is this actually AI-powered?", a: "No — and we're not going to pretend otherwise. The bundle content is generated by deterministic templates, not a language model. There's nothing to wait for, nothing that can hallucinate, and nothing that needs an API key." },
  {
    q: "Which AI coding tools are supported?",
    a: "GitHub Copilot, Claude Code, Cursor, Windsurf, Cline, Continue.dev, Aider, and the open, multi-vendor AGENTS.md convention. Pick as many as your team actually uses — each one gets its own correctly-formatted file(s) from the same underlying content. See the Guides page for exactly how each tool reads its file.",
  },
  {
    q: "Which stacks are supported, and can I combine them?",
    a: "22 stacks across six categories: Languages (Python, Java, Go, Rust, TypeScript), Backend & APIs (FastAPI, Django, Node.js, Spring Boot, Ruby on Rails, C#/.NET), Frontend (React, Next.js, Vue, Angular), Database (PostgreSQL, MongoDB, SQL/Prisma), Mobile (Flutter/Dart), and Tools (Docker/Kubernetes, Terraform, Tailwind CSS). Check as many as apply to build a real-world combination like Python + FastAPI + React + MongoDB — there's no limit on how many you combine.",
  },
  {
    q: "How does the agent know about cross-stack workflows?",
    a: "Whenever your selection spans multiple layers, a Cross-Stack Guardrails section is added automatically — generic rules for any frontend+backend, backend+database, or full-stack combination, plus curated guidance for specific, common pairings like React+FastAPI, Next.js+Prisma or FastAPI+MongoDB. It's how the agent knows a database migration isn't done until the backend model and the frontend that depends on it are updated too.",
  },
  { q: "Does the zip extract cleanly into my project?", a: "Yes. Every file sits at its real project-root-relative path inside the zip — extracting it directly into your project root populates .github/, CLAUDE.md, .cursor/, .agent.md, etc. immediately, with no extra wrapper folder." },
  { q: "Is anything sent to a server?", a: "No. Stack selection, mode, target selection, bundle generation and the zip file are all built in your browser. Your last picks are remembered in your browser's local storage only, so they're there next time you open the page — nothing is uploaded anywhere." },
  { q: "Can I edit the generated files afterward?", a: "Yes, and you should. They're a strong, opinionated starting point, not a rulebook carved in stone — trim, extend or reword any directive to match how your team actually works. The Guides page has tips on what's worth customizing first." },
];

export default function HomePage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-10 sm:py-14">
      <JsonLd
        data={[
          softwareAppLd({
            name: "Agent Hub",
            description: "Free generator combining multiple stacks into one cross-stack-aware AI coding agent, or separate per-stack files, for GitHub Copilot, Claude Code, Cursor, Windsurf, Cline, Continue.dev, Aider and AGENTS.md.",
            path: "/",
            keywords: ["ai coding agent generator", "multi-stack ai agent", "github copilot instructions generator", "claude code CLAUDE.md generator", "cursor rules generator"],
          }),
          faqLd(FAQS),
        ]}
      />
      <header className="mb-8 text-center">
        <p className="mx-auto inline-flex items-center gap-1.5 font-mono text-xs font-semibold uppercase tracking-wide text-[var(--color-accent)]">
          <span className="h-1.5 w-1.5 rounded-full bg-[var(--color-accent)]" /> 22 stacks · combine any of them · 8 AI coding tools
        </p>
        <h1 className="mt-2 text-3xl font-bold tracking-tight text-[var(--color-ink)] sm:text-4xl">Configure your full-stack AI coding agent</h1>
        <p className="mx-auto mt-3 max-w-xl text-[var(--color-muted)]">
          Build a real combination — Python + FastAPI + React + MongoDB, or whatever your repo actually runs — and merge it into one cross-stack-aware
          agent, or keep each stack in its own file. Every bundle enforces 10 strict operating directives, the Universal Guardrails (code quality, error
          handling, token efficiency, security), and a mandatory end-of-session impact chart, packaged correctly for GitHub Copilot, Claude Code, Cursor,
          Windsurf, Cline, Continue.dev, Aider or AGENTS.md. Preview every file, then download the zip. No sign-up, nothing leaves your browser.
        </p>
      </header>
      <AgentHub />
      <section className="mt-16">
        <h2 className="text-lg font-semibold text-[var(--color-ink)]">Questions</h2>
        <div className="mt-3 divide-y divide-[var(--color-border)] rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)]">
          {FAQS.map((f) => (
            <details key={f.q} className="group p-5">
              <summary className="flex cursor-pointer list-none items-center justify-between font-medium text-[var(--color-ink)]">
                {f.q}
                <span className="text-[var(--color-accent)] transition group-open:rotate-45">+</span>
              </summary>
              <p className="mt-3 text-sm text-[var(--color-muted)]">{f.a}</p>
            </details>
          ))}
        </div>
      </section>
    </div>
  );
}
